services:
    rabbitmq:
        image: rabbitmq:management-alpine

        container_name: rabbitmq

        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"

        networks:
            - report-system-network

        volumes:
            - rabbitmq-data:/var/lib/rabbitmq/
            - rabbitmq-logs:/var/log/rabbitmq/

    sqlserver:
        container_name: sqlserver2019

        image: mcr.microsoft.com/mssql/server:2019-latest

        volumes:
            - sqlserver-data:/var/opt/mssql

        environment:
            SA_PASSWORD: "#DevEnv123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"

        ports:
            - "127.0.0.1:1430:1433"

        networks:
            - report-system-network

        restart: unless-stopped
            
networks:
    report-system-network:
        driver: bridge

volumes:
    rabbitmq-data:
    rabbitmq-logs:
    sqlserver-data:

